/*
Company (required) -              : ICON
CODE NAME (required)              : AE_SMQ700
PROJECT NAME (required)           :  
DESCRIPTION (required)            :  
SPECIFICATIONS (required)         : 
VALIDATION TYPE (required)        : 
INDEPENDENT REPLICATION (required): N/A
ORIGINAL CODE (required)          : N/A, this is the original code
COMPONENT CODE MODULES            : N/A
SOFTWARE/VERSION# (required)      : SAS 9.4
INFRASTRUCTURE                    : 
DATA INPUT                        : AE3001A and B
OUTPUT                            : AE_SMQ700
SPECIAL INSTRUCTIONS              : N/A
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
DOCUMENTATION AND REVISION HISTORY SECTION (required):

       Author &
Ver# Validator        Code History Description
---- ------------     ------------------------------------------------------------------------
1.0  Joe Cooney   Original version of the code
*/

proc sql;
create table AE as
select SUBJID, AEGRPID, AETERM, AEDECOD
   from clntrial.AE3001A
   where aedecod in ('Electrocardiogram QT interval abnormal',
'Electrocardiogram QT prolonged',
'Long QT syndrome',
'Long QT syndrome congenital',
'Torsade de pointes',
'Ventricular tachycardia',
'Cardiac arrest',
'Cardiac death',
'Cardiac fibrillation',
'Cardio-respiratory arrest',
'Electrocardiogram repolarisation abnormality',
'Electrocardiogram U-wave abnormality',
'Loss of consciousness',
'Sudden cardiac death',
'Sudden death',
'Syncope',
'Ventricular arrhythmia',
'Ventricular fibrillation',
'Ventricular flutter',
'Ventricular tachyarrhythmia',
 'Acute aortic syndrome',
'Acute myocardial infarction',
'Amaurosis',
'Amaurosis fugax',
'Angioplasty',
'Aortic bypass',
'Aortic embolus',
'Aortic surgery',
'Aortic thrombosis',
'Aortogram abnormal',
'Arterectomy',
'Arterectomy with graft replacement',
'Arterial bypass occlusion',
'Arterial bypass operation',
'Arterial bypass thrombosis',
'Arterial graft',
'Arterial occlusive disease',
'Arterial stent insertion',
'Arterial therapeutic procedure',
'Arterial thrombosis',
'Arteriogram abnormal',
'Arteriogram carotid abnormal',
'Atherectomy',
'Atherosclerotic plaque rupture',
'Basal ganglia infarction',
'Basilar artery occlusion',
'Basilar artery thrombosis',
'Blindness transient',
'Brachiocephalic artery occlusion',
'Capsular warning syndrome',
'Carotid angioplasty',
'Carotid arterial embolus',
'Carotid artery bypass',
'Carotid artery occlusion',
'Carotid artery stent insertion',
'Carotid artery thrombosis',
'Carotid endarterectomy',
'Cerebellar artery occlusion',
'Cerebellar artery thrombosis',
'Cerebral artery embolism',
'Cerebral artery occlusion',
'Cerebral artery thrombosis',
'Cerebral hypoperfusion',
'Cerebrovascular insufficiency',
'Cerebrovascular stenosis',
'Coeliac artery occlusion',
'Coronary angioplasty',
'Coronary arterial stent insertion',
'Coronary artery bypass',
'Coronary artery embolism',
'Coronary artery occlusion',
'Coronary artery reocclusion',
'Coronary artery thrombosis',
'Coronary endarterectomy',
'Coronary revascularisation',
'Coronary vascular graft occlusion',
'Embolia cutis medicamentosa',
'Embolism arterial',
'Endarterectomy',
'Femoral artery embolism',
'Hepatic artery embolism',
'Hepatic artery occlusion',
'Hepatic artery thrombosis',
'Hypothenar hammer syndrome',
'Iliac artery embolism',
'Iliac artery occlusion',
'Intra-aortic balloon placement',
'Intraoperative cerebral artery occlusion',
'Ischaemic cerebral infarction',
'Ischaemic stroke',
'Lacunar infarction',
'Left atrial appendage occlusion',
'Leriche syndrome',
'Mesenteric arterial occlusion',
'Mesenteric arteriosclerosis',
'Mesenteric artery embolism',
'Mesenteric artery stenosis',
'Mesenteric artery stent insertion',
'Mesenteric artery thrombosis',
'Myocardial infarction',
'Myocardial necrosis',
'Papillary muscle infarction',
'Penile artery occlusion',
'Percutaneous coronary intervention',
'Peripheral arterial occlusive disease',
'Peripheral arterial reocclusion',
'Peripheral artery angioplasty',
'Peripheral artery bypass',
'Peripheral artery occlusion',
'Peripheral artery stent insertion',
'Peripheral artery thrombosis',
'Peripheral embolism',
'Peripheral endarterectomy',
'Popliteal artery entrapment syndrome',
'Post procedural myocardial infarction',
'Postinfarction angina',
'Precerebral artery occlusion',
'Precerebral artery thrombosis',
'Pulmonary artery therapeutic procedure',
'Pulmonary artery thrombosis',
'Pulmonary endarterectomy',
'Renal artery angioplasty',
'Renal artery occlusion',
'Renal artery thrombosis',
'Renal embolism',
'Retinal artery embolism',
'Retinal artery occlusion',
'Retinal artery thrombosis',
'Silent myocardial infarction',
'Spinal artery embolism',
'Spinal artery thrombosis',
'Splenic artery thrombosis',
'Splenic embolism',
'Stress cardiomyopathy',
'Stroke in evolution',
'Subclavian artery embolism',
'Subclavian artery occlusion',
'Subclavian artery thrombosis',
'Superior mesenteric artery syndrome',
'Thromboembolectomy',
'Thrombotic microangiopathy',
'Thrombotic thrombocytopenic purpura',
'Transient ischaemic attack',
'Truncus coeliacus thrombosis',
'Vertebral artery occlusion',
'Vertebral artery thrombosis',
'Visual acuity reduced transiently',
'Axillary vein thrombosis',
'Brachiocephalic vein occlusion',
'Budd-Chiari syndrome',
'Catheterisation venous',
'Cavernous sinus thrombosis',
'Central venous catheterisation',
'Cerebral venous thrombosis',
'Compression stockings application',
'Deep vein thrombosis',
'Deep vein thrombosis postoperative',
'Embolism venous',
'Hepatic vein occlusion',
'Hepatic vein thrombosis',
'Homans'' sign positive',
'Iliac vein occlusion',
'Inferior vena cava syndrome',
'Inferior vena caval occlusion',
'Intracranial venous sinus thrombosis',
'Jugular vein occlusion',
'Jugular vein thrombosis',
'Mahler sign',
'May-Thurner syndrome',
'Mesenteric vein thrombosis',
'Mesenteric venous occlusion',
'Obstetrical pulmonary embolism',
'Obstructive shock',
'Ophthalmic vein thrombosis',
'Ovarian vein thrombosis',
'Paget-Schroetter syndrome',
'Pelvic venous thrombosis',
'Penile vein thrombosis',
'Phlebectomy',
'Portal vein cavernous transformation',
'Portal vein occlusion',
'Portal vein thrombosis',
'Portosplenomesenteric venous thrombosis',
'Post procedural pulmonary embolism',
'Post thrombotic syndrome',
'Postoperative thrombosis',
'Postpartum venous thrombosis',
'Pulmonary embolism',
'Pulmonary infarction',
'Pulmonary microemboli',
'Pulmonary thrombosis',
'Pulmonary vein occlusion',
'Pulmonary veno-occlusive disease',
'Pulmonary venous thrombosis',
'Renal vein embolism',
'Renal vein occlusion',
'Renal vein thrombosis',
'Retinal vein occlusion',
'Retinal vein thrombosis',
'SI QIII TIII pattern',
'Splenic vein occlusion',
'Splenic vein thrombosis',
'Subclavian vein thrombosis',
'Superior sagittal sinus thrombosis',
'Superior vena cava occlusion',
'Superior vena cava syndrome',
'Thrombophlebitis',
'Thrombophlebitis migrans',
'Thrombophlebitis neonatal',
'Thrombophlebitis superficial',
'Thrombosed varicose vein',
'Thrombosis corpora cavernosa',
'Transverse sinus thrombosis',
'Vena cava embolism',
'Vena cava filter insertion',
'Vena cava filter removal',
'Vena cava thrombosis',
'Venogram abnormal',
'Venoocclusive disease',
'Venoocclusive liver disease',
'Venous angioplasty',
'Venous occlusion',
'Venous operation',
'Venous recanalisation',
'Venous repair',
'Venous stent insertion',
'Venous thrombosis',
'Venous thrombosis in pregnancy',
'Venous thrombosis limb',
'Venous thrombosis neonatal',
'Visceral venous thrombosis',
'Administration site thrombosis',
'Adrenal thrombosis',
'Angiogram abnormal',
'Angiogram cerebral abnormal',
'Angiogram peripheral abnormal',
'Application site thrombosis',
'Arteriovenous fistula occlusion',
'Arteriovenous fistula thrombosis',
'Arteriovenous graft thrombosis',
'Atrial thrombosis',
'Basal ganglia stroke',
'Bone infarction',
'Brain stem embolism',
'Brain stem infarction',
'Brain stem stroke',
'Brain stem thrombosis',
'Cardiac ventricular thrombosis',
'Cerebellar embolism',
'Cerebellar infarction',
'Cerebral congestion',
'Cerebral infarction',
'Cerebral infarction foetal',
'Cerebral ischaemia',
'Cerebral septic infarct',
'Cerebral thrombosis',
'Cerebral vascular occlusion',
'Cerebrospinal thrombotic tamponade',
'Cerebrovascular accident',
'Cerebrovascular accident prophylaxis',
'Cerebrovascular disorder',
'Cerebrovascular operation',
'Choroidal infarction',
'Collateral circulation',
'Coronary bypass thrombosis',
'Device embolisation',
'Device occlusion',
'Device related thrombosis',
'Diplegia',
'Directional Doppler flow tests abnormal',
'Disseminated intravascular coagulation',
'Disseminated intravascular coagulation in newborn',
'Embolic cerebral infarction',
'Embolic pneumonia',
'Embolic stroke',
'Embolism',
'Foetal cerebrovascular disorder',
'Graft thrombosis',
'Haemorrhagic cerebral infarction',
'Haemorrhagic infarction',
'Haemorrhagic stroke',
'Haemorrhagic transformation stroke',
'Haemorrhoids thrombosed',
'Hemiparesis',
'Hemiplegia',
'Heparin-induced thrombocytopenia',
'Hepatic infarction',
'Hepatic vascular thrombosis',
'Implant site thrombosis',
'Incision site vessel occlusion',
'Infarction',
'Infusion site thrombosis',
'Injection site thrombosis',
'Inner ear infarction',
'Instillation site thrombosis',
'Intestinal infarction',
'Intracardiac mass',
'Intracardiac thrombus',
'Medical device site thrombosis',
'Mesenteric vascular insufficiency',
'Mesenteric vascular occlusion',
'Microembolism',
'Monoparesis',
'Monoplegia',
'Optic nerve infarction',
'Pancreatic infarction',
'Paradoxical embolism',
'Paraparesis',
'Paraplegia',
'Paresis',
'Peripheral revascularisation',
'Pituitary infarction',
'Placental infarction',
'Pneumatic compression therapy',
'Portal shunt procedure',
'Post procedural stroke',
'Postpartum thrombosis',
'Prosthetic vessel implantation',
'Quadriparesis',
'Quadriplegia',
'Renal infarct',
'Renal vascular thrombosis',
'Retinal infarction',
'Retinal vascular thrombosis',
'Shunt occlusion',
'Shunt thrombosis',
'Spinal cord infarction',
'Splenic infarction',
'Splenic thrombosis',
'Stoma site thrombosis',
'Surgical vascular shunt',
'Testicular infarction',
'Thalamic infarction',
'Thrombectomy',
'Thromboangiitis obliterans',
'Thrombolysis',
'Thrombosis',
'Thrombosis in device',
'Thrombosis mesenteric vessel',
'Thrombosis prophylaxis',
'Thrombotic cerebral infarction',
'Thrombotic stroke',
'Thyroid infarction',
'Tumour embolism',
'Tumour thrombosis',
'Ultrasonic angiogram abnormal',
'Ultrasound Doppler abnormal',
'Umbilical cord occlusion',
'Umbilical cord thrombosis',
'Vaccination site thrombosis',
'Vascular graft',
'Vascular graft occlusion',
'Vascular graft thrombosis',
'Vascular operation',
'Vascular stent insertion',
'Vascular stent occlusion',
'Vascular stent thrombosis',
'Vasodilation procedure',
'Vessel puncture site occlusion',
'Vessel puncture site thrombosis',
'Visual midline shift syndrome',
'Acute left ventricular failure',
'Acute pulmonary oedema',
'Acute right ventricular failure',
'Cardiac asthma',
'Cardiac failure',
'Cardiac failure acute',
'Cardiac failure chronic',
'Cardiac failure congestive',
'Cardiac failure high output',
'Cardiogenic shock',
'Cardiopulmonary failure',
'Cardiorenal syndrome',
'Chronic left ventricular failure',
'Chronic right ventricular failure',
'Cor pulmonale',
'Cor pulmonale acute',
'Cor pulmonale chronic',
'Ejection fraction decreased',
'Hepatic congestion',
'Hepatojugular reflux',
'Left ventricular failure',
'Low cardiac output syndrome',
'Neonatal cardiac failure',
'Obstructive shock',
'Pulmonary oedema',
'Pulmonary oedema neonatal',
'Radiation associated cardiac failure',
'Right ventricular ejection fraction decreased',
'Right ventricular failure',
'Ventricular failure',
'Artificial heart implant',
'Atrial natriuretic peptide abnormal',
'Atrial natriuretic peptide increased',
'Bendopnoea',
'Brain natriuretic peptide abnormal',
'Brain natriuretic peptide increased',
'Cardiac cirrhosis',
'Cardiac contractility modulation therapy',
'Cardiac index decreased',
'Cardiac output decreased',
'Cardiac resynchronisation therapy',
'Cardiac ventriculogram abnormal',
'Cardiac ventriculogram left abnormal',
'Cardiac ventriculogram right abnormal',
'Cardiomegaly',
'Cardio-respiratory distress',
'Cardiothoracic ratio increased',
'Central venous pressure increased',
'Diastolic dysfunction',
'Dilatation ventricular',
'Dyspnoea paroxysmal nocturnal',
'Heart transplant',
'Hepatic vein dilatation',
'Jugular vein distension',
'Left ventricular dysfunction',
'Lower respiratory tract congestion',
'Myocardial depression',
'Nocturnal dyspnoea',
'N-terminal prohormone brain natriuretic peptide abnormal',
'N-terminal prohormone brain natriuretic peptide increased',
'Oedema',
'Oedema due to cardiac disease',
'Oedema neonatal',
'Oedema peripheral',
'Orthopnoea',
'Peripheral oedema neonatal',
'Peripheral swelling',
'Prohormone brain natriuretic peptide abnormal',
'Prohormone brain natriuretic peptide increased',
'Pulmonary congestion',
'Right ventricular dysfunction',
'Scan myocardial perfusion abnormal',
'Stroke volume decreased',
'Systolic dysfunction',
'Venous pressure increased',
'Venous pressure jugular abnormal',
'Venous pressure jugular increased',
'Ventricular assist device insertion',
'Ventricular dysfunction',
'Ventricular dyssynchrony',
'Acute coronary syndrome',
'Acute myocardial infarction',
'Angina unstable',
'Blood creatine phosphokinase MB abnormal',
'Blood creatine phosphokinase MB increased',
'Coronary artery embolism',
'Coronary artery occlusion',
'Coronary artery reocclusion',
'Coronary artery thrombosis',
'Coronary bypass thrombosis',
'Coronary vascular graft occlusion',
'Kounis syndrome',
'Myocardial infarction',
'Myocardial necrosis',
'Myocardial reperfusion injury',
'Myocardial stunning',
'Papillary muscle infarction',
'Post procedural myocardial infarction',
'Postinfarction angina',
'Silent myocardial infarction',
'Troponin I increased',
'Troponin increased',
'Troponin T increased',
'Blood creatine phosphokinase abnormal',
'Blood creatine phosphokinase increased',
'Cardiac ventricular scarring',
'ECG electrically inactive area',
'ECG signs of myocardial infarction',
'Electrocardiogram Q wave abnormal',
'Electrocardiogram ST segment abnormal',
'Electrocardiogram ST segment elevation',
'Electrocardiogram ST-T segment elevation',
'Infarction',
'Myocardial necrosis marker increased',
'Scan myocardial perfusion abnormal',
'Vascular graft occlusion',
'Vascular stent occlusion',
'Vascular stent thrombosis',
'Angina pectoris',
'Angina unstable',
'Anginal equivalent',
'Arteriosclerosis coronary artery',
'Arteriospasm coronary',
'Coronary angioplasty',
'Coronary arterial stent insertion',
'Coronary artery bypass',
'Coronary artery disease',
'Coronary artery dissection',
'Coronary artery insufficiency',
'Coronary artery restenosis',
'Coronary artery stenosis',
'Coronary brachytherapy',
'Coronary bypass stenosis',
'Coronary endarterectomy',
'Coronary no-reflow phenomenon',
'Coronary ostial stenosis',
'Coronary revascularisation',
'Coronary vascular graft stenosis',
'Dissecting coronary artery aneurysm',
'ECG signs of myocardial ischaemia',
'External counterpulsation',
'Haemorrhage coronary artery',
'Ischaemic cardiomyopathy',
'Ischaemic mitral regurgitation',
'Microvascular coronary artery disease',
'Myocardial ischaemia',
'Percutaneous coronary intervention',
'Prinzmetal angina',
'Stress cardiomyopathy',
'Subclavian coronary steal syndrome',
'Subendocardial ischaemia',
'Arteriogram coronary abnormal',
'Cardiac stress test abnormal',
'Cardiopulmonary exercise test abnormal',
'Computerised tomogram coronary artery abnormal',
'Electrocardiogram ST segment depression',
'Electrocardiogram ST-T segment abnormal',
'Electrocardiogram ST-T segment depression',
'Electrocardiogram T wave abnormal',
'Electrocardiogram T wave inversion',
'Exercise electrocardiogram abnormal',
'Exercise test abnormal',
'Post angioplasty restenosis',
'Stress echocardiogram abnormal',
'Vascular stent restenosis',
'Vascular stent stenosis',
'Balint''s syndrome',
'Basilar artery aneurysm',
'Carotid artery aneurysm',
'Carotid artery dissection',
'Cerebral endovascular aneurysm repair',
'Cerebral reperfusion injury',
'Cerebral ventricular rupture',
'Cerebrovascular accident prophylaxis',
'Charcot-Bouchard microaneurysms',
'Congenital hemiparesis',
'CSF bilirubin positive',
'Hemianaesthesia',
'Hemiasomatognosia',
'Hemiparesis',
'Hemiplegia',
'Intra-cerebral aneurysm operation',
'Intracranial aneurysm',
'Post stroke depression',
'Vein of Galen aneurysmal malformation',
'Vertebral artery aneurysm',
'Vertebral artery dissection',
'Agnosia',
'Angiogram cerebral abnormal',
'Aphasia',
'Brain injury',
'Central pain syndrome',
'Cerebral haemosiderin deposition',
'CSF red blood cell count positive',
'Diplegia',
'Dysarthria',
'Internal carotid artery kinking',
'Intracranial artery dissection',
'Modified Rankin score decreased',
'Modified Rankin score increased',
'Monoparesis',
'Monoplegia',
'NIH stroke scale abnormal',
'NIH stroke scale score decreased',
'NIH stroke scale score increased',
'Paralysis',
'Paraparesis',
'Paraplegia',
'Paresis',
'Quadriparesis',
'Quadriplegia',
'Right hemisphere deficit syndrome',
'Superficial siderosis of central nervous system',
'Visual agnosia',
'Visual midline shift syndrome',
'Basal ganglia haematoma',
'Basal ganglia haemorrhage',
'Basal ganglia stroke',
'Basilar artery perforation',
'Brain stem haematoma',
'Brain stem haemorrhage',
'Brain stem microhaemorrhage',
'Brain stem stroke',
'Carotid aneurysm rupture',
'Carotid artery perforation',
'Central nervous system haemorrhage',
'Cerebellar haematoma',
'Cerebellar haemorrhage',
'Cerebellar microhaemorrhage',
'Cerebral aneurysm perforation',
'Cerebral aneurysm ruptured syphilitic',
'Cerebral arteriovenous malformation haemorrhagic',
'Cerebral artery perforation',
'Cerebral haematoma',
'Cerebral haemorrhage',
'Cerebral haemorrhage foetal',
'Cerebral haemorrhage neonatal',
'Cerebral microhaemorrhage',
'Cerebrovascular accident',
'Cerebrovascular disorder',
'Epidural haemorrhage',
'Extradural haematoma',
'Haemorrhage intracranial',
'Haemorrhagic cerebral infarction',
'Haemorrhagic stroke',
'Haemorrhagic transformation stroke',
'Intracerebral haematoma evacuation',
'Intracranial haematoma',
'Intracranial tumour haemorrhage',
'Intraventricular haemorrhage',
'Intraventricular haemorrhage neonatal',
'Meningorrhagia',
'Perinatal stroke',
'Periventricular haemorrhage neonatal',
'Pituitary haemorrhage',
'Putamen haemorrhage',
'Ruptured cerebral aneurysm',
'Spinal cord haematoma',
'Spinal cord haemorrhage',
'Spinal epidural haematoma',
'Spinal epidural haemorrhage',
'Spinal subarachnoid haemorrhage',
'Spinal subdural haematoma',
'Spinal subdural haemorrhage',
'Stroke in evolution',
'Subarachnoid haematoma',
'Subarachnoid haemorrhage',
'Subarachnoid haemorrhage neonatal',
'Subdural haematoma',
'Subdural haematoma evacuation',
'Subdural haemorrhage',
'Subdural haemorrhage neonatal',
'Thalamus haemorrhage',
'Vertebral artery perforation',
'Amaurosis fugax',
'Basal ganglia infarction',
'Basal ganglia stroke',
'Basilar artery occlusion',
'Basilar artery stenosis',
'Basilar artery thrombosis',
'Brachiocephalic arteriosclerosis',
'Brachiocephalic artery occlusion',
'Brachiocephalic artery stenosis',
'Brain hypoxia',
'Brain stem embolism',
'Brain stem infarction',
'Brain stem ischaemia',
'Brain stem stroke',
'Brain stem thrombosis',
'Capsular warning syndrome',
'Carotid angioplasty',
'Carotid arterial embolus',
'Carotid arteriosclerosis',
'Carotid artery bypass',
'Carotid artery disease',
'Carotid artery insufficiency',
'Carotid artery occlusion',
'Carotid artery restenosis',
'Carotid artery stenosis',
'Carotid artery stent insertion',
'Carotid artery stent removal',
'Carotid artery thrombosis',
'Carotid endarterectomy',
'Carotid revascularisation',
'Cerebellar artery occlusion',
'Cerebellar artery thrombosis',
'Cerebellar embolism',
'Cerebellar infarction',
'Cerebellar ischaemia',
'Cerebral arteriosclerosis',
'Cerebral artery embolism',
'Cerebral artery occlusion',
'Cerebral artery restenosis',
'Cerebral artery stenosis',
'Cerebral artery thrombosis',
'Cerebral gas embolism',
'Cerebral infarction',
'Cerebral infarction foetal',
'Cerebral ischaemia',
'Cerebral revascularisation',
'Cerebral septic infarct',
'Cerebral small vessel ischaemic disease',
'Cerebral thrombosis',
'Cerebral vascular occlusion',
'Cerebral vasoconstriction',
'Cerebral venous thrombosis',
'Cerebrovascular accident',
'Cerebrovascular disorder',
'Cerebrovascular insufficiency',
'Cerebrovascular stenosis',
'Embolic cerebral infarction',
'Embolic stroke',
'Hypoxic-ischaemic encephalopathy',
'Inner ear infarction',
'Ischaemic cerebral infarction',
'Ischaemic stroke',
'Lacunar infarction',
'Lacunar stroke',
'Lateral medullary syndrome',
'Migrainous infarction',
'Millard-Gubler syndrome',
'Moyamoya disease',
'Perinatal stroke',
'Post procedural stroke',
'Precerebral arteriosclerosis',
'Precerebral artery occlusion',
'Reversible cerebral vasoconstriction syndrome',
'Reversible ischaemic neurological deficit',
'Spinal artery embolism',
'Spinal artery thrombosis',
'Stroke in evolution',
'Subclavian steal syndrome',
'Thalamic infarction',
'Thrombotic cerebral infarction',
'Thrombotic stroke',
'Transient ischaemic attack',
'Vascular encephalopathy',
'Vascular stent occlusion',
'Vascular stent restenosis',
'Vascular stent stenosis',
'Vertebral artery occlusion',
'Vertebral artery stenosis',
'Vertebral artery thrombosis',
'Vertebrobasilar insufficiency',
'Cerebral arteritis',
'Cerebral capillary telangiectasia',
'Cerebral circulatory failure',
'Cerebral congestion',
'Cerebral hypoperfusion',
'Dural arteriovenous fistula',
'Intracranial venous sinus thrombosis',
'Superior sagittal sinus thrombosis',
'Transverse sinus thrombosis',
'Vasculitis cerebral',
'Amyloid related imaging abnormalities',
'Blood brain barrier defect',
'Cerebral amyloid angiopathy',
'Cerebral microangiopathy',
'Cerebrovascular arteriovenous malformation',
'Congenital cerebrovascular anomaly',
'Fahr''s disease',
'Foetal cerebrovascular disorder',
'Hypertensive cerebrovascular disease',
'Sneddon''s syndrome',
'Spinal vascular disorder',
'Spinal vessel congenital anomaly',
'Susac''s syndrome',
'Vertebrobasilar dolichoectasia',
'Chronotropic incompetence',
'Electrocardiogram repolarisation abnormality',
'Electrocardiogram RR interval prolonged',
'Electrocardiogram U-wave abnormality',
'Sudden cardiac death',
'Bezold-Jarisch reflex',
'Bradycardia',
'Cardiac arrest',
'Cardiac death',
'Cardiac telemetry abnormal',
'Cardio-respiratory arrest',
'Electrocardiogram abnormal',
'Electrocardiogram ambulatory abnormal',
'Electrocardiogram change',
'Heart rate abnormal',
'Heart rate decreased',
'Heart rate increased',
'Loss of consciousness',
'Palpitations',
'Rebound tachycardia',
'Sudden death',
'Syncope',
'Tachycardia',
'Tachycardia paroxysmal',
'Bradyarrhythmia',
'Ventricular asystole',
'Accessory cardiac pathway',
'Adams-Stokes syndrome',
'Agonal rhythm',
'Atrial conduction time prolongation',
'Atrioventricular block',
'Atrioventricular block complete',
'Atrioventricular block first degree',
'Atrioventricular block second degree',
'Atrioventricular conduction time shortened',
'Atrioventricular dissociation',
'Bifascicular block',
'Brugada syndrome',
'Bundle branch block',
'Bundle branch block bilateral',
'Bundle branch block left',
'Bundle branch block right',
'Conduction disorder',
'Defect conduction intraventricular',
'Electrocardiogram delta waves abnormal',
'Electrocardiogram PQ interval prolonged',
'Electrocardiogram PQ interval shortened',
'Electrocardiogram PR prolongation',
'Electrocardiogram PR shortened',
'Electrocardiogram QRS complex prolonged',
'Electrocardiogram QT prolonged',
'Electrocardiogram repolarisation abnormality',
'Lenegre''s disease',
'Long QT syndrome',
'Paroxysmal atrioventricular block',
'Sinoatrial block',
'Trifascicular block',
'Ventricular dyssynchrony',
'Wolff-Parkinson-White syndrome',
'Nodal arrhythmia',
'Nodal rhythm',
'Sinus arrest',
'Sinus arrhythmia',
'Sinus bradycardia',
'Sinus node dysfunction',
'Wandering pacemaker',
'Arrhythmia',
'Heart alternation',
'Heart rate irregular',
'Pacemaker generated arrhythmia',
'Pacemaker syndrome',
'Paroxysmal arrhythmia',
'Pulseless electrical activity',
'Reperfusion arrhythmia',
'Withdrawal arrhythmia',
'Arrhythmia supraventricular',
'Atrial fibrillation',
'Atrial flutter',
'Atrial parasystole',
'Atrial tachycardia',
'Junctional ectopic tachycardia',
'Sinus tachycardia',
'Supraventricular extrasystoles',
'Supraventricular tachyarrhythmia',
'Supraventricular tachycardia',
'ECG P wave inverted',
'Electrocardiogram P wave abnormal',
'Retrograde p-waves',
'Anomalous atrioventricular excitation',
'Cardiac fibrillation',
'Cardiac flutter',
'Extrasystoles',
'Tachyarrhythmia',
'Accelerated idioventricular rhythm',
'Cardiac fibrillation',
'Parasystole',
'Rhythm idioventricular',
'Torsade de pointes',
'Ventricular arrhythmia',
'Ventricular extrasystoles',
'Ventricular fibrillation',
'Ventricular flutter',
'Ventricular parasystole',
'Ventricular pre-excitation',
'Ventricular tachyarrhythmia',
'Ventricular tachycardia',
'Arrhythmia neonatal',
'Arrhythmogenic right ventricular dysplasia',
'Atrioventricular node dispersion',
'Brugada syndrome',
'Foetal arrhythmia',
'Foetal heart rate disorder',
'Foetal tachyarrhythmia',
'Heart block congenital',
'Junctional ectopic tachycardia',
'Long QT syndrome congenital',
'Lown-Ganong-Levine syndrome',
'Wolff-Parkinson-White syndrome congenital',
'Baseline foetal heart rate variability disorder',
'Bradycardia foetal',
'Bradycardia neonatal',
'Cardiac arrest neonatal',
'Cardio-respiratory arrest neonatal',
'Foetal heart rate acceleration abnormality',
'Foetal heart rate deceleration abnormality',
'Neonatal tachycardia',
'Nonreassuring foetal heart rate pattern',
'Tachycardia foetal',
'Accelerated hypertension',
'Blood pressure ambulatory increased',
'Blood pressure diastolic increased',
'Blood pressure inadequately controlled',
'Blood pressure increased',
'Blood pressure management',
'Blood pressure orthostatic increased',
'Blood pressure systolic increased',
'Diastolic hypertension',
'Eclampsia',
'Endocrine hypertension',
'Essential hypertension',
'Gestational hypertension',
'HELLP syndrome',
'Hyperaldosteronism',
'Hypertension',
'Hypertension neonatal',
'Hypertensive angiopathy',
'Hypertensive cardiomegaly',
'Hypertensive cardiomyopathy',
'Hypertensive cerebrovascular disease',
'Hypertensive crisis',
'Hypertensive emergency',
'Hypertensive encephalopathy',
'Hypertensive heart disease',
'Hypertensive nephropathy',
'Labile hypertension',
'Malignant hypertension',
'Malignant hypertensive heart disease',
'Malignant renal hypertension',
'Maternal hypertension affecting foetus',
'Mean arterial pressure increased',
'Metabolic syndrome',
'Neurogenic hypertension',
'Orthostatic hypertension',
'Page kidney',
'Pre-eclampsia',
'Prehypertension',
'Procedural hypertension',
'Renal hypertension',
'Renal sympathetic nerve ablation',
'Renovascular hypertension',
'Retinopathy hypertensive',
'Secondary aldosteronism',
'Secondary hypertension',
'Systolic hypertension',
'Withdrawal hypertension',
'Aldosterone urine abnormal',
'Aldosterone urine increased',
'Angiotensin converting enzyme increased',
'Angiotensin I increased',
'Angiotensin II increased',
'Blood aldosterone abnormal',
'Blood aldosterone increased',
'Blood catecholamines abnormal',
'Blood catecholamines increased',
'Blood pressure abnormal',
'Blood pressure ambulatory abnormal',
'Blood pressure diastolic abnormal',
'Blood pressure fluctuation',
'Blood pressure orthostatic abnormal',
'Blood pressure systolic abnormal',
'Catecholamines urine abnormal',
'Catecholamines urine increased',
'Diuretic therapy',
'Ectopic aldosterone secretion',
'Ectopic renin secretion',
'Epinephrine abnormal',
'Epinephrine increased',
'Labile blood pressure',
'Metanephrine urine abnormal',
'Metanephrine urine increased',
'Non-dipping',
'Norepinephrine abnormal',
'Norepinephrine increased',
'Normetanephrine urine increased',
'Pseudoaldosteronism',
'Renin abnormal',
'Renin increased',
'Renin-angiotensin system inhibition',
'Tyramine reaction',
 'Atrial septal defect acquired',
'Biopsy heart abnormal',
'Cardiac amyloidosis',
'Cardiac hypertrophy',
'Cardiac sarcoidosis',
'Cardiac septal hypertrophy',
'Cardiac siderosis',
'Cardiomyopathy',
'Cardiomyopathy acute',
'Cardiomyopathy alcoholic',
'Cardiomyopathy neonatal',
'Cardiotoxicity',
'Congestive cardiomyopathy',
'Cytotoxic cardiomyopathy',
'Diabetic cardiomyopathy',
'Ejection fraction abnormal',
'Ejection fraction decreased',
'Eosinophilic myocarditis',
'HIV cardiomyopathy',
'Hypertensive cardiomyopathy',
'Hypertrophic cardiomyopathy',
'Ischaemic cardiomyopathy',
'Metabolic cardiomyopathy',
'Myocardial calcification',
'Myocardial fibrosis',
'Myocardial haemorrhage',
'Non-obstructive cardiomyopathy',
'Peripartum cardiomyopathy',
'Pulmonary arterial wedge pressure increased') or AEDECOD in (
'Restrictive cardiomyopathy',
'Right ventricular ejection fraction decreased',
'Stress cardiomyopathy',
'Tachycardia induced cardiomyopathy',
'Thyrotoxic cardiomyopathy',
'Ventricular septal defect acquired',
'Viral cardiomyopathy',
'Abnormal precordial movement',
'Acquired cardiac septal defect',
'Acute left ventricular failure',
'Alcohol septal ablation',
'Allergic myocarditis',
'Arrhythmia',
'Arrhythmia supraventricular',
'Artificial heart implant',
'Ascites',
'Atrial hypertrophy',
'Atrial pressure increased',
'Autoimmune myocarditis',
'Bendopnoea',
'Blood pressure diastolic abnormal',
'Blood pressure diastolic decreased',
'Blood pressure diastolic increased',
'Blood pressure fluctuation',
'Blood pressure inadequately controlled',
'Blood pressure systolic abnormal',
'Blood pressure systolic decreased',
'Blood pressure systolic increased',
'Cardiac aneurysm',
'Cardiac arrest',
'Cardiac contractility modulation therapy',
'Cardiac electrophysiologic study abnormal',
'Cardiac failure',
'Cardiac failure acute',
'Cardiac failure chronic',
'Cardiac failure congestive',
'Cardiac function test abnormal',
'Cardiac imaging procedure abnormal',
'Cardiac index abnormal',
'Cardiac index decreased',
'Cardiac index increased',
'Cardiac monitoring abnormal',
'Cardiac operation',
'Cardiac output decreased',
'Cardiac pseudoaneurysm',
'Cardiac resynchronisation therapy',
'Cardiac ventricular scarring',
'Cardiac ventriculogram abnormal',
'Cardiac ventriculogram left abnormal',
'Cardiac ventriculogram right abnormal',
'Cardiomegaly',
'Cardiothoracic ratio increased',
'Cardiovascular disorder',
'Cardiovascular function test abnormal',
'Chest pain',
'Chest X-ray abnormal',
'Computerised tomogram thorax abnormal',
'Coxsackie carditis',
'Coxsackie myocarditis',
'Cytomegalovirus myocarditis',
'Decreased ventricular preload',
'Diastolic dysfunction',
'Dilatation atrial',
'Dilatation ventricular',
'Directional Doppler flow tests abnormal',
'Dyspnoea',
'ECG signs of ventricular hypertrophy',
'Echocardiogram abnormal',
'Electrocardiogram abnormal',
'Electrocardiogram change',
'Endocardial fibroelastosis',
'External counterpulsation',
'Heart and lung transplant',
'Heart transplant',
'Hepatomegaly',
'Hyperdynamic left ventricle',
'Increased ventricular preload',
'Irregular breathing',
'Labile blood pressure',
'Left atrial dilatation',
'Left ventricular end-diastolic pressure decreased',
'Left ventricular failure',
'Left ventricular heave',
'Lupus myocarditis',
'Malarial myocarditis',
'Mental status changes',
'Multiple gated acquisition scan abnormal',
'Myocardiac abscess',
'Myocardial necrosis marker increased',
'Myocarditis',
'Myocarditis bacterial',
'Myocarditis helminthic',
'Myocarditis infectious',
'Myocarditis meningococcal',
'Myocarditis mycotic',
'Myocarditis post infection',
'Myocarditis septic',
'Myocarditis syphilitic',
'Myocarditis toxoplasmal',
'Myoglobinaemia',
'Myoglobinuria',
'Nocturia',
'Nuclear magnetic resonance imaging thoracic abnormal',
'Oedema',
'Orthostatic hypotension',
'Palpitations',
'Papillary muscle disorder',
'Papillary muscle haemorrhage',
'Radiation myocarditis',
'Reduction ventriculoplasty',
'Right atrial dilatation',
'Right atrial pressure increased',
'Right ventricle outflow tract obstruction',
'Right ventricular heave',
'Right ventricular systolic pressure decreased',
'Scan myocardial perfusion abnormal',
'Sudden cardiac death',
'Sudden death',
'Syncope',
'Systolic anterior motion of mitral valve',
'Systolic dysfunction',
'Ultrasound Doppler abnormal',
'Vascular resistance pulmonary increased',
'Ventricular arrhythmia',
'Ventricular assist device insertion',
'Ventricular dysfunction',
'Ventricular dyskinesia',
'Ventricular dyssynchrony',
'Ventricular hyperkinesia',
'Ventricular hypertrophy',
'Ventricular hypokinesia',
'Ventricular remodelling',
'Viral myocarditis',
'Acute right ventricular failure',
'Cardiac ventriculogram right abnormal',
'Central venous pressure increased',
'Chronic right ventricular failure',
'Cor pulmonale',
'Cor pulmonale acute',
'Cor pulmonale chronic',
'Portopulmonary hypertension',
'Pulmonary arterial hypertension',
'Pulmonary arterial pressure abnormal',
'Pulmonary arterial pressure increased',
'Pulmonary arterial wedge pressure increased',
'Pulmonary artery dilatation',
'Pulmonary artery wall hypertrophy',
'Pulmonary capillary haemangiomatosis',
'Pulmonary endarterectomy',
'Pulmonary hypertension',
'Pulmonary hypertensive crisis',
'Pulmonary valve incompetence',
'Pulmonary vascular resistance abnormality',
'Pulmonary vein occlusion',
'Pulmonary vein stenosis',
'Pulmonary veno-occlusive disease',
'Right atrial dilatation',
'Right atrial hypertrophy',
'Right atrial pressure increased',
'Right ventricular dysfunction',
'Right ventricular failure',
'Right ventricular heave',
'Right ventricular hypertension',
'Right ventricular hypertrophy',
'Right ventricular systolic pressure increased',
'Tricuspid valve incompetence',
'Vascular resistance pulmonary increased',
'Abnormal precordial movement',
'Angiogram pulmonary abnormal',
'Atrial pressure increased',
'Banti''s syndrome',
'Bendopnoea',
'Brain natriuretic peptide increased',
'Cardiac cirrhosis',
'Cardiac index decreased',
'Cardiac murmur',
'Carotid pulse decreased',
'Combined pulmonary fibrosis and emphysema',
'Cyanosis central',
'Diastolic dysfunction',
'Dilatation ventricular',
'Dizziness exertional',
'Dyspnoea',
'Dyspnoea at rest',
'Dyspnoea exertional',
'Dyspnoea paroxysmal nocturnal',
'Exercise test abnormal',
'Heart sounds abnormal',
'Hepatojugular reflux',
'Hypoxia',
'Increased ventricular afterload',
'Increased ventricular preload',
'Irregular breathing',
'Jugular vein distension',
'Left ventricular end-diastolic pressure decreased',
'Non-cirrhotic portal hypertension',
'Oedema due to cardiac disease',
'Orthopnoea',
'Pulmonary arterial wedge pressure abnormal',
'Pulmonary arteriopathy',
'Pulmonary vascular disorder',
'Respiratory fatigue',
'Stroke volume decreased',
'Tricuspid valve prolapse',
'Tricuspid valve repair',
'Tricuspid valve replacement',
'Tricuspid valve sclerosis',
'Venous pressure jugular increased',
'Abdominal pain',
'Abdominal pain upper',
'Abdominal pain lower')
ORDER by SUBJID;
quit;

/*SITE*/

proc sql;
create table site as
select distinct st.SITEMNEMONIC, SUBJID
from clntrial.inf_sub sb, clntrial.inf_site st, clntrial.SV1001 dm
where sb.SITEGUID=st.CT_RECID and dm.subject_id=sb.subject_id
order by SUBJID;
quit;

data AE_SMQ700;
retain SITEMNEMONIC SUBJID AEGRPID AETERM AEDECOD;
merge AE(in=a) site;
by SUBJID;
if a;
run;

/*Print AE_SMQ700*/
ods csv file=&irfilcsv trantab=ascii;
  title1 "AE_SMQ700";
title2 "Output where AEDECOD = any of the PTs included on the SMQs Combined list .";
  proc print data=AE_SMQ700 noobs WIDTH=min; 
    var _all_;
  run;
ods csv close;

/*Create output for no observations*/
data _null_;
file print;
if 0 then set AE_SMQ700 nobs=NUM; 
if NUM=0 then do;
        put /// @21 "There are no records found";
        end;
stop;
