select distinct

a.MERGE_DATETIME,
b.SITEMNEMONIC, 
a.SUBJID, 
a.TULNKID_TARGET, 
a.TRLNKID_TU2F1, 
a.TRSPID_TU2F1,
a.TRPERF,
a.TRMETHOD_TU2F1,
a.TRMETHODOTH_TU2F1

from

((select distinct x.* from

(select a.SUBJID, a.MERGE_DATETIME, a.TULNKID_TARGET, b.TRLNKID_TU2F1, b.TRSPID_TU2F1, b.TRPERF, b.TRMETHOD_TU2F1, b.TRMETHODOTH_TU2F1

from

(select SUBJID, MERGE_DATETIME, TULNKID_TARGET from I5B_MC_JGDJ.TU2001A_All
where page in ('TU2001_F1')) a

left join

(select SUBJID, TRLNKID_TU2F1, TRSPID_TU2F1, TRPERF, TRMETHOD_TU2F1, TRMETHODOTH_TU2F1 from I5B_MC_JGDJ.TU2001B_All
where page in ('TU2001_F1')) b

on a.SUBJID = b.SUBJID and a.TULNKID_TARGET = b.TRLNKID_TU2F1) x,

(select a.SUBJID, a.MERGE_DATETIME, a.TULNKID_TARGET, b.TRLNKID_TU2F1, b.TRSPID_TU2F1, b.TRPERF, b.TRMETHOD_TU2F1, b.TRMETHODOTH_TU2F1

from

(select SUBJID, MERGE_DATETIME, TULNKID_TARGET from I5B_MC_JGDJ.TU2001A_All
where page in ('TU2001_F1')) a

left join

(select SUBJID, TRLNKID_TU2F1, TRSPID_TU2F1, TRPERF, TRMETHOD_TU2F1, TRMETHODOTH_TU2F1 from I5B_MC_JGDJ.TU2001B_All
where page in ('TU2001_F1')) b

on a.SUBJID = b.SUBJID and a.TULNKID_TARGET = b.TRLNKID_TU2F1) y

where x.SUBJID=y.SUBJID and x.TRSPID_TU2F1 = y.TRSPID_TU2F1 
      and x.TULNKID_TARGET != y.TULNKID_TARGET and x.TRMETHOD_TU2F1 != y.TRMETHOD_TU2F1)
      

Union All

(select distinct x.* from


(select a.SUBJID, a.MERGE_DATETIME, a.TULNKID_TARGET, b.TRLNKID_TU2F1, b.TRSPID_TU2F1, b.TRPERF, b.TRMETHOD_TU2F1, b.TRMETHODOTH_TU2F1

from

(select SUBJID, MERGE_DATETIME, TULNKID_TARGET from I5B_MC_JGDJ.TU2001A_All
where page in ('TU2001_F1')) a

left join

(select SUBJID, TRLNKID_TU2F1, TRSPID_TU2F1, TRPERF, TRMETHOD_TU2F1, TRMETHODOTH_TU2F1 from I5B_MC_JGDJ.TU2001B_All
where page in ('TU2001_F1')) b

on a.SUBJID = b.SUBJID and a.TULNKID_TARGET = b.TRLNKID_TU2F1) x,

(select a.SUBJID, a.MERGE_DATETIME, a.TULNKID_TARGET, b.TRLNKID_TU2F1, b.TRSPID_TU2F1, b.TRPERF, b.TRMETHOD_TU2F1, b.TRMETHODOTH_TU2F1

from

(select SUBJID, MERGE_DATETIME, TULNKID_TARGET from I5B_MC_JGDJ.TU2001A_All
where page in ('TU2001_F1')) a

left join

(select SUBJID, TRLNKID_TU2F1, TRSPID_TU2F1, TRPERF, TRMETHOD_TU2F1, TRMETHODOTH_TU2F1 from I5B_MC_JGDJ.TU2001B_All
where page in ('TU2001_F1')) b

on a.SUBJID = b.SUBJID and a.TULNKID_TARGET = b.TRLNKID_TU2F1) y

where x.SUBJID=y.SUBJID and x.TRSPID_TU2F1 = y.TRSPID_TU2F1 
      and x.TULNKID_TARGET != y.TULNKID_TARGET and x.TRMETHODOTH_TU2F1 != y.TRMETHODOTH_TU2F1)) a

left join (select dm.SUBJECT_ID,SUBJID,SEX,st.SITEMNEMONIC
                      from I5B_MC_JGDJ.inf_subject sb, I5B_MC_JGDJ.inf_site_update st, I5B_MC_JGDJ.DM1001_all dm
                      where sb.SITEGUID=st.CT_RECID and dm.subject_id=sb.subject_id) b
on a.SUBJID=b.SUBJID